context:
  version: "0.3.2"

package:
  name: celq
  version: ${{ version }}

source:
  url: https://github.com/IvanIsCoding/celq/archive/v${{ version }}.tar.gz
  sha256: 3549643b29ff628d060a4ca8d1ebf4f57ba9f5055aa374c86d7dee29b8d0dd27

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - celq -n -b --void "1 > 0"

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: A CEL command-line query tool for JSON data
  homepage: https://github.com/IvanIsCoding/celq
  repository: https://github.com/IvanIsCoding/celq
  documentation: https://docs.rs/celq/latest/celq/

extra:
  recipe-maintainers:
    - IvanIsCoding
