context:
  version: "0.4.0"

package:
  name: celq
  version: ${{ version }}

source:
  url: https://github.com/IvanIsCoding/celq/archive/v${{ version }}.tar.gz
  sha256: 63e2e5a902112c45d3752c0f89ace620c1ea8695d37413f36818580303f537d9

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - celq -n -b --void "1 > 0"

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: A CEL command-line query tool for JSON data
  homepage: https://github.com/IvanIsCoding/celq
  repository: https://github.com/IvanIsCoding/celq
  documentation: https://docs.rs/celq/latest/celq/

extra:
  recipe-maintainers:
    - IvanIsCoding
